# netlify.toml
# =====================================
# Proxy all API requests to your Render backend
[[redirects]]
  from = "/api/*"
  to = "https://wildroots-api.onrender.com/api/:splat"
  status = 200
  force = true

# SPA catch-all — serve React app for everything else
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
# =====================================
